import { Header } from '@/widgets/header'
import type { Metadata } from 'next'
import StoreProvider from '../providers/store-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en">
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
      <link
        href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap"
        rel="stylesheet"
      />

      <body>
        <StoreProvider>
          <Header />
          <main className="p-4 mx-auto">{children}</main>
        </StoreProvider>
      </body>
    </html>
  )
}
