import { Header } from '@/widgets/header'
import type { Metadata } from 'next'
import StoreProvider from '../providers/store-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <Header />
          <main className="p-4 mx-auto">{children}</main>
        </StoreProvider>
      </body>
    </html>
  )
}
